root = "/app"  # Соответствует WORKDIR в Dockerfile

[build]
cmd = "go build -o /app/documentum ./cmd/main.go"  # Или другой путь к main
bin = "/app/documentum"
full_bin = "/app/documentum"
include_ext = ["go", "html", "tpl", "tmpl", "json", "sql"]
exclude_dir = ["vendor", "logs", "tmp"]
delay = 1000
stop_on_error = true

[log]
time = false
show_timestamp = true