services:
    # MySQL Database Service
  db:
    image: mysql:5.7.43
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3306:3306"
    restart: unless-stopped
  
  #GO server
  app:
    image: alpine:3.21.3
    volumes:
      - ./.env:/app/.env
      - ./documentum:/app/documentum  
      - ./web:/app/web/
      - ./logs/documentum.log:/app/logs/documentum.log
    command: "/app/documentum"
    ports:
      - "8000:8000"
    depends_on:
      - db

  #Adminer
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  mysql_data:
  