services:
    # MySQL Database Service
  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    restart: unless-stopped
  
  #Adminer
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
  
  #GO server
  app:
    build: .
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy  
    restart: unless-stopped
    command: air -c .air.toml 
    volumes:
      - .:/app
      - /go/pkg/mod 

volumes:
  mysql_data:
 
  